Lixuan/md 706/new app server ui free

diff --git a/appserver b/appserver
--- a/appserver
+++ b/appserver
@@ -16,12 +16,10 @@ else
 fi
 
 if [ "$1" = "-h" ]; then
-  echo "Usage : appserver [local|remote|create_image|build]"
+  echo "Usage : appserver [local|build]"
   echo ""
   echo "Commands : "
   echo "   local                        Start docker container with local database and mqtt service"
-  echo "   remote                       Start docker container with remote database and mqtt service;"
-  echo "   create_image                 Create compiled docker image for LPWAN-app-server"
   echo "   build                        Command for building the code, only run in docker container"
   echo ""
   exit
@@ -82,7 +80,7 @@ obtain_certificate()
   cp "$PARENT_PATH"/testing-framework/gRPC-client/certificates/ps-staging.matchx.io/ecc_rootCA.pem "$PARENT_PATH"/configuration/ecc/ecc_rootCA.pem
 }
 
-if [ "$*" = "remote" ] || [ "$*" = "local" ]; then
+if [ "$*" = "local" ]; then
   if [ -f "/.dockerenv" ]; then
      echo "Command '$0 $*' only runs outside of a docker container, nothing is executed. "
      exit
@@ -90,7 +88,6 @@ if [ "$*" = "remote" ] || [ "$*" = "local" ]; then
 
   python "$PARENT_PATH"/scripts/docker/docker-compose-template.py \
     "env_file"=$CONFIG \
-    "supernode_data_service"="$*" \
     "supernode_mode"=$supernode_mode |tee tmp
 
   [ "$(cat tmp)" = "invalid argument" ] && exit
@@ -122,31 +119,23 @@ elif [ "$*" = "create_image" ]; then
      exit
   fi
 
-  python "$PARENT_PATH"/scripts/docker/docker-compose-template.py \
-    "env_file"=$CONFIG \
-    "supernode_data_service"='image' \
-    "supernode_mode"='image' |tee tmp
-
-  [ "$(cat tmp)" = "invalid argument" ] && exit
-
-  if [ -f "$PARENT_PATH"/docker-compose-create-image.yml ]; then
-    mv "$PARENT_PATH"/docker-compose-create-image.yml "$PARENT_PATH"/docker-compose-create-image.ymlbak
+  if ! [ -f "$PARENT_PATH"/docker-compose-create-image.yml ]; then
+     echo "Cannot create docker image, $PARENT_PATH/docker-compose-create-image.yml not exists "
+     exit
   fi
 
-  mv tmp "$PARENT_PATH"/docker-compose-create-image.yml
-
   if [ -z "$DOCKER_HUB_USERNAME" ]; then
-    read -p "Insert docker hub username: " USERNAME
+    read -rp "Insert docker hub username: " USERNAME
     export DOCKER_HUB_USERNAME=$USERNAME
   fi
 
   if [ -z "$DOCKER_HUB_PASSWORD" ]; then
-    read -p "Insert docker hub password: " PASSWORD
+    read -rp "Insert docker hub password: " PASSWORD
     export DOCKER_HUB_PASSWORD=$PASSWORD
   fi
 
   if [ -z "$DOCKER_HUB_REPOSITORY" ]; then
-    read -p "Insert docker hub repository: " REPOSITORY
+    read -rp "Insert docker hub repository: " REPOSITORY
     export DOCKER_HUB_REPOSITORY=$REPOSITORY
   fi
 
